### ISSUE TITLE
model_opts differs between DeepDive and DeepNSD

### ISSUE THREAD

**Issue by PhilippKaniuth** [ColinConwell/DeepDive#3]
Cool project!

This [DeepDive](https://github.com/ColinConwell/DeepDive) repository seems to be the home of your convenience functions that load and instrumentalize different DNNs. The main package is _model_opts_. Over in the [DeepNSD](https://github.com/ColinConwell/DeepNSD) repository, you also use that package _model_opts_.

However, it seems that _model_opts_ in DeepNSD is more uptodate than the original one here in DeepDive? If I get this right, from January onwards a few commits were made to DeepNSD's _model_opts_, including a bug fix, but not to DeepDive's.

This leaves me somewhat confused as to which repository to use if I want to utilize DeepDive only (independently from the benchmark repos)?

Maybe it makes sense to embeed DeepDive as a [submodule](https://github.blog/2016-02-01-working-with-submodules/) into DeepNSD.

Thanks for your work!

**Comment by ColinConwell** [comment]
@PhilippKaniuth Right you are. This is mostly an artifact of my not yet having turned DeepDive into its own package, though I suppose I could circumvent this with a two-stage download (DeepNSD files, then DeepDive model_opts).

At the moment, DeepNSD has the most up-to-date version of the model_opts. This will ideally change sometime soon when I get around to making DeepDive an actual package.

**Comment by ColinConwell** [comment]
DeepNSD has been modified to now only use DeepDive! (The tutorial pulls from the brain data from the DeepNSD repo and the modeling code from this repo.)
